// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: keyvalue.proto
// Protobuf Java Version: 4.31.0

package com.yrrhelp.proto;

/**
 * Protobuf type {@code GetOperationLogRequest}
 */
@com.google.protobuf.Generated
public final class GetOperationLogRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:GetOperationLogRequest)
    GetOperationLogRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      GetOperationLogRequest.class.getName());
  }
  // Use GetOperationLogRequest.newBuilder() to construct.
  private GetOperationLogRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetOperationLogRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yrrhelp.proto.Keyvalue.internal_static_GetOperationLogRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yrrhelp.proto.Keyvalue.internal_static_GetOperationLogRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yrrhelp.proto.GetOperationLogRequest.class, com.yrrhelp.proto.GetOperationLogRequest.Builder.class);
  }

  public static final int FROM_TIMESTAMP_FIELD_NUMBER = 1;
  private long fromTimestamp_ = 0L;
  /**
   * <code>int64 from_timestamp = 1;</code>
   * @return The fromTimestamp.
   */
  @java.lang.Override
  public long getFromTimestamp() {
    return fromTimestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (fromTimestamp_ != 0L) {
      output.writeInt64(1, fromTimestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (fromTimestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, fromTimestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yrrhelp.proto.GetOperationLogRequest)) {
      return super.equals(obj);
    }
    com.yrrhelp.proto.GetOperationLogRequest other = (com.yrrhelp.proto.GetOperationLogRequest) obj;

    if (getFromTimestamp()
        != other.getFromTimestamp()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FROM_TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFromTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yrrhelp.proto.GetOperationLogRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yrrhelp.proto.GetOperationLogRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yrrhelp.proto.GetOperationLogRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yrrhelp.proto.GetOperationLogRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yrrhelp.proto.GetOperationLogRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yrrhelp.proto.GetOperationLogRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yrrhelp.proto.GetOperationLogRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.yrrhelp.proto.GetOperationLogRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.yrrhelp.proto.GetOperationLogRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.yrrhelp.proto.GetOperationLogRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yrrhelp.proto.GetOperationLogRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.yrrhelp.proto.GetOperationLogRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yrrhelp.proto.GetOperationLogRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetOperationLogRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetOperationLogRequest)
      com.yrrhelp.proto.GetOperationLogRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yrrhelp.proto.Keyvalue.internal_static_GetOperationLogRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yrrhelp.proto.Keyvalue.internal_static_GetOperationLogRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yrrhelp.proto.GetOperationLogRequest.class, com.yrrhelp.proto.GetOperationLogRequest.Builder.class);
    }

    // Construct using com.yrrhelp.proto.GetOperationLogRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fromTimestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yrrhelp.proto.Keyvalue.internal_static_GetOperationLogRequest_descriptor;
    }

    @java.lang.Override
    public com.yrrhelp.proto.GetOperationLogRequest getDefaultInstanceForType() {
      return com.yrrhelp.proto.GetOperationLogRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.yrrhelp.proto.GetOperationLogRequest build() {
      com.yrrhelp.proto.GetOperationLogRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.yrrhelp.proto.GetOperationLogRequest buildPartial() {
      com.yrrhelp.proto.GetOperationLogRequest result = new com.yrrhelp.proto.GetOperationLogRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.yrrhelp.proto.GetOperationLogRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.fromTimestamp_ = fromTimestamp_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yrrhelp.proto.GetOperationLogRequest) {
        return mergeFrom((com.yrrhelp.proto.GetOperationLogRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yrrhelp.proto.GetOperationLogRequest other) {
      if (other == com.yrrhelp.proto.GetOperationLogRequest.getDefaultInstance()) return this;
      if (other.getFromTimestamp() != 0L) {
        setFromTimestamp(other.getFromTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              fromTimestamp_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long fromTimestamp_ ;
    /**
     * <code>int64 from_timestamp = 1;</code>
     * @return The fromTimestamp.
     */
    @java.lang.Override
    public long getFromTimestamp() {
      return fromTimestamp_;
    }
    /**
     * <code>int64 from_timestamp = 1;</code>
     * @param value The fromTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setFromTimestamp(long value) {

      fromTimestamp_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 from_timestamp = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      fromTimestamp_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:GetOperationLogRequest)
  }

  // @@protoc_insertion_point(class_scope:GetOperationLogRequest)
  private static final com.yrrhelp.proto.GetOperationLogRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yrrhelp.proto.GetOperationLogRequest();
  }

  public static com.yrrhelp.proto.GetOperationLogRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetOperationLogRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetOperationLogRequest>() {
    @java.lang.Override
    public GetOperationLogRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetOperationLogRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetOperationLogRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.yrrhelp.proto.GetOperationLogRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

