// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: keyvalue.proto
// Protobuf Java Version: 4.31.0

package com.yrrhelp.proto;

@com.google.protobuf.Generated
public interface GetOperationLogResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetOperationLogResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Operation operations = 1;</code>
   */
  java.util.List<com.yrrhelp.proto.Operation> 
      getOperationsList();
  /**
   * <code>repeated .Operation operations = 1;</code>
   */
  com.yrrhelp.proto.Operation getOperations(int index);
  /**
   * <code>repeated .Operation operations = 1;</code>
   */
  int getOperationsCount();
  /**
   * <code>repeated .Operation operations = 1;</code>
   */
  java.util.List<? extends com.yrrhelp.proto.OperationOrBuilder> 
      getOperationsOrBuilderList();
  /**
   * <code>repeated .Operation operations = 1;</code>
   */
  com.yrrhelp.proto.OperationOrBuilder getOperationsOrBuilder(
      int index);
}
