// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: keyvalue.proto
// Protobuf Java Version: 4.31.0

package com.yrrhelp.proto;

/**
 * Protobuf type {@code GetOperationLogResponse}
 */
@com.google.protobuf.Generated
public final class GetOperationLogResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:GetOperationLogResponse)
    GetOperationLogResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      GetOperationLogResponse.class.getName());
  }
  // Use GetOperationLogResponse.newBuilder() to construct.
  private GetOperationLogResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetOperationLogResponse() {
    operations_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yrrhelp.proto.Keyvalue.internal_static_GetOperationLogResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yrrhelp.proto.Keyvalue.internal_static_GetOperationLogResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yrrhelp.proto.GetOperationLogResponse.class, com.yrrhelp.proto.GetOperationLogResponse.Builder.class);
  }

  public static final int OPERATIONS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.yrrhelp.proto.Operation> operations_;
  /**
   * <code>repeated .Operation operations = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.yrrhelp.proto.Operation> getOperationsList() {
    return operations_;
  }
  /**
   * <code>repeated .Operation operations = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.yrrhelp.proto.OperationOrBuilder> 
      getOperationsOrBuilderList() {
    return operations_;
  }
  /**
   * <code>repeated .Operation operations = 1;</code>
   */
  @java.lang.Override
  public int getOperationsCount() {
    return operations_.size();
  }
  /**
   * <code>repeated .Operation operations = 1;</code>
   */
  @java.lang.Override
  public com.yrrhelp.proto.Operation getOperations(int index) {
    return operations_.get(index);
  }
  /**
   * <code>repeated .Operation operations = 1;</code>
   */
  @java.lang.Override
  public com.yrrhelp.proto.OperationOrBuilder getOperationsOrBuilder(
      int index) {
    return operations_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < operations_.size(); i++) {
      output.writeMessage(1, operations_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < operations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, operations_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yrrhelp.proto.GetOperationLogResponse)) {
      return super.equals(obj);
    }
    com.yrrhelp.proto.GetOperationLogResponse other = (com.yrrhelp.proto.GetOperationLogResponse) obj;

    if (!getOperationsList()
        .equals(other.getOperationsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getOperationsCount() > 0) {
      hash = (37 * hash) + OPERATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOperationsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yrrhelp.proto.GetOperationLogResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yrrhelp.proto.GetOperationLogResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yrrhelp.proto.GetOperationLogResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yrrhelp.proto.GetOperationLogResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yrrhelp.proto.GetOperationLogResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yrrhelp.proto.GetOperationLogResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yrrhelp.proto.GetOperationLogResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.yrrhelp.proto.GetOperationLogResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.yrrhelp.proto.GetOperationLogResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.yrrhelp.proto.GetOperationLogResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yrrhelp.proto.GetOperationLogResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.yrrhelp.proto.GetOperationLogResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yrrhelp.proto.GetOperationLogResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetOperationLogResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetOperationLogResponse)
      com.yrrhelp.proto.GetOperationLogResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yrrhelp.proto.Keyvalue.internal_static_GetOperationLogResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yrrhelp.proto.Keyvalue.internal_static_GetOperationLogResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yrrhelp.proto.GetOperationLogResponse.class, com.yrrhelp.proto.GetOperationLogResponse.Builder.class);
    }

    // Construct using com.yrrhelp.proto.GetOperationLogResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (operationsBuilder_ == null) {
        operations_ = java.util.Collections.emptyList();
      } else {
        operations_ = null;
        operationsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yrrhelp.proto.Keyvalue.internal_static_GetOperationLogResponse_descriptor;
    }

    @java.lang.Override
    public com.yrrhelp.proto.GetOperationLogResponse getDefaultInstanceForType() {
      return com.yrrhelp.proto.GetOperationLogResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.yrrhelp.proto.GetOperationLogResponse build() {
      com.yrrhelp.proto.GetOperationLogResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.yrrhelp.proto.GetOperationLogResponse buildPartial() {
      com.yrrhelp.proto.GetOperationLogResponse result = new com.yrrhelp.proto.GetOperationLogResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.yrrhelp.proto.GetOperationLogResponse result) {
      if (operationsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          operations_ = java.util.Collections.unmodifiableList(operations_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.operations_ = operations_;
      } else {
        result.operations_ = operationsBuilder_.build();
      }
    }

    private void buildPartial0(com.yrrhelp.proto.GetOperationLogResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yrrhelp.proto.GetOperationLogResponse) {
        return mergeFrom((com.yrrhelp.proto.GetOperationLogResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yrrhelp.proto.GetOperationLogResponse other) {
      if (other == com.yrrhelp.proto.GetOperationLogResponse.getDefaultInstance()) return this;
      if (operationsBuilder_ == null) {
        if (!other.operations_.isEmpty()) {
          if (operations_.isEmpty()) {
            operations_ = other.operations_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOperationsIsMutable();
            operations_.addAll(other.operations_);
          }
          onChanged();
        }
      } else {
        if (!other.operations_.isEmpty()) {
          if (operationsBuilder_.isEmpty()) {
            operationsBuilder_.dispose();
            operationsBuilder_ = null;
            operations_ = other.operations_;
            bitField0_ = (bitField0_ & ~0x00000001);
            operationsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetOperationsFieldBuilder() : null;
          } else {
            operationsBuilder_.addAllMessages(other.operations_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.yrrhelp.proto.Operation m =
                  input.readMessage(
                      com.yrrhelp.proto.Operation.parser(),
                      extensionRegistry);
              if (operationsBuilder_ == null) {
                ensureOperationsIsMutable();
                operations_.add(m);
              } else {
                operationsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.yrrhelp.proto.Operation> operations_ =
      java.util.Collections.emptyList();
    private void ensureOperationsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        operations_ = new java.util.ArrayList<com.yrrhelp.proto.Operation>(operations_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.yrrhelp.proto.Operation, com.yrrhelp.proto.Operation.Builder, com.yrrhelp.proto.OperationOrBuilder> operationsBuilder_;

    /**
     * <code>repeated .Operation operations = 1;</code>
     */
    public java.util.List<com.yrrhelp.proto.Operation> getOperationsList() {
      if (operationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(operations_);
      } else {
        return operationsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Operation operations = 1;</code>
     */
    public int getOperationsCount() {
      if (operationsBuilder_ == null) {
        return operations_.size();
      } else {
        return operationsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Operation operations = 1;</code>
     */
    public com.yrrhelp.proto.Operation getOperations(int index) {
      if (operationsBuilder_ == null) {
        return operations_.get(index);
      } else {
        return operationsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Operation operations = 1;</code>
     */
    public Builder setOperations(
        int index, com.yrrhelp.proto.Operation value) {
      if (operationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOperationsIsMutable();
        operations_.set(index, value);
        onChanged();
      } else {
        operationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Operation operations = 1;</code>
     */
    public Builder setOperations(
        int index, com.yrrhelp.proto.Operation.Builder builderForValue) {
      if (operationsBuilder_ == null) {
        ensureOperationsIsMutable();
        operations_.set(index, builderForValue.build());
        onChanged();
      } else {
        operationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Operation operations = 1;</code>
     */
    public Builder addOperations(com.yrrhelp.proto.Operation value) {
      if (operationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOperationsIsMutable();
        operations_.add(value);
        onChanged();
      } else {
        operationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Operation operations = 1;</code>
     */
    public Builder addOperations(
        int index, com.yrrhelp.proto.Operation value) {
      if (operationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOperationsIsMutable();
        operations_.add(index, value);
        onChanged();
      } else {
        operationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Operation operations = 1;</code>
     */
    public Builder addOperations(
        com.yrrhelp.proto.Operation.Builder builderForValue) {
      if (operationsBuilder_ == null) {
        ensureOperationsIsMutable();
        operations_.add(builderForValue.build());
        onChanged();
      } else {
        operationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Operation operations = 1;</code>
     */
    public Builder addOperations(
        int index, com.yrrhelp.proto.Operation.Builder builderForValue) {
      if (operationsBuilder_ == null) {
        ensureOperationsIsMutable();
        operations_.add(index, builderForValue.build());
        onChanged();
      } else {
        operationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Operation operations = 1;</code>
     */
    public Builder addAllOperations(
        java.lang.Iterable<? extends com.yrrhelp.proto.Operation> values) {
      if (operationsBuilder_ == null) {
        ensureOperationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, operations_);
        onChanged();
      } else {
        operationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Operation operations = 1;</code>
     */
    public Builder clearOperations() {
      if (operationsBuilder_ == null) {
        operations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        operationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Operation operations = 1;</code>
     */
    public Builder removeOperations(int index) {
      if (operationsBuilder_ == null) {
        ensureOperationsIsMutable();
        operations_.remove(index);
        onChanged();
      } else {
        operationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Operation operations = 1;</code>
     */
    public com.yrrhelp.proto.Operation.Builder getOperationsBuilder(
        int index) {
      return internalGetOperationsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Operation operations = 1;</code>
     */
    public com.yrrhelp.proto.OperationOrBuilder getOperationsOrBuilder(
        int index) {
      if (operationsBuilder_ == null) {
        return operations_.get(index);  } else {
        return operationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Operation operations = 1;</code>
     */
    public java.util.List<? extends com.yrrhelp.proto.OperationOrBuilder> 
         getOperationsOrBuilderList() {
      if (operationsBuilder_ != null) {
        return operationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(operations_);
      }
    }
    /**
     * <code>repeated .Operation operations = 1;</code>
     */
    public com.yrrhelp.proto.Operation.Builder addOperationsBuilder() {
      return internalGetOperationsFieldBuilder().addBuilder(
          com.yrrhelp.proto.Operation.getDefaultInstance());
    }
    /**
     * <code>repeated .Operation operations = 1;</code>
     */
    public com.yrrhelp.proto.Operation.Builder addOperationsBuilder(
        int index) {
      return internalGetOperationsFieldBuilder().addBuilder(
          index, com.yrrhelp.proto.Operation.getDefaultInstance());
    }
    /**
     * <code>repeated .Operation operations = 1;</code>
     */
    public java.util.List<com.yrrhelp.proto.Operation.Builder> 
         getOperationsBuilderList() {
      return internalGetOperationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.yrrhelp.proto.Operation, com.yrrhelp.proto.Operation.Builder, com.yrrhelp.proto.OperationOrBuilder> 
        internalGetOperationsFieldBuilder() {
      if (operationsBuilder_ == null) {
        operationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.yrrhelp.proto.Operation, com.yrrhelp.proto.Operation.Builder, com.yrrhelp.proto.OperationOrBuilder>(
                operations_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        operations_ = null;
      }
      return operationsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:GetOperationLogResponse)
  }

  // @@protoc_insertion_point(class_scope:GetOperationLogResponse)
  private static final com.yrrhelp.proto.GetOperationLogResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yrrhelp.proto.GetOperationLogResponse();
  }

  public static com.yrrhelp.proto.GetOperationLogResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetOperationLogResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetOperationLogResponse>() {
    @java.lang.Override
    public GetOperationLogResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetOperationLogResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetOperationLogResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.yrrhelp.proto.GetOperationLogResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

