// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: keyvalue.proto
// Protobuf Java Version: 4.31.0

package com.yrrhelp.proto;

@com.google.protobuf.Generated
public interface HeartbeatInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeartbeatInfoRequest)
    com.google.protobuf.MessageOrBuilder {
}
