// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: keyvalue.proto
// Protobuf Java Version: 4.31.0

package com.yrrhelp.proto;

@com.google.protobuf.Generated
public interface HeartbeatInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeartbeatInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * node_id -&gt; timestamp
   * </pre>
   *
   * <code>map&lt;string, int64&gt; last_heartbeat = 1;</code>
   */
  int getLastHeartbeatCount();
  /**
   * <pre>
   * node_id -&gt; timestamp
   * </pre>
   *
   * <code>map&lt;string, int64&gt; last_heartbeat = 1;</code>
   */
  boolean containsLastHeartbeat(
      java.lang.String key);
  /**
   * Use {@link #getLastHeartbeatMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Long>
  getLastHeartbeat();
  /**
   * <pre>
   * node_id -&gt; timestamp
   * </pre>
   *
   * <code>map&lt;string, int64&gt; last_heartbeat = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.Long>
  getLastHeartbeatMap();
  /**
   * <pre>
   * node_id -&gt; timestamp
   * </pre>
   *
   * <code>map&lt;string, int64&gt; last_heartbeat = 1;</code>
   */
  long getLastHeartbeatOrDefault(
      java.lang.String key,
      long defaultValue);
  /**
   * <pre>
   * node_id -&gt; timestamp
   * </pre>
   *
   * <code>map&lt;string, int64&gt; last_heartbeat = 1;</code>
   */
  long getLastHeartbeatOrThrow(
      java.lang.String key);
}
