// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: keyvalue.proto
// Protobuf Java Version: 4.31.0

package com.yrrhelp.proto;

/**
 * Protobuf type {@code HeartbeatInfoResponse}
 */
@com.google.protobuf.Generated
public final class HeartbeatInfoResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:HeartbeatInfoResponse)
    HeartbeatInfoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      HeartbeatInfoResponse.class.getName());
  }
  // Use HeartbeatInfoResponse.newBuilder() to construct.
  private HeartbeatInfoResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private HeartbeatInfoResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.yrrhelp.proto.Keyvalue.internal_static_HeartbeatInfoResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 1:
        return internalGetLastHeartbeat();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.yrrhelp.proto.Keyvalue.internal_static_HeartbeatInfoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.yrrhelp.proto.HeartbeatInfoResponse.class, com.yrrhelp.proto.HeartbeatInfoResponse.Builder.class);
  }

  public static final int LAST_HEARTBEAT_FIELD_NUMBER = 1;
  private static final class LastHeartbeatDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Long> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Long>newDefaultInstance(
                com.yrrhelp.proto.Keyvalue.internal_static_HeartbeatInfoResponse_LastHeartbeatEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.INT64,
                0L);
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Long> lastHeartbeat_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
  internalGetLastHeartbeat() {
    if (lastHeartbeat_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          LastHeartbeatDefaultEntryHolder.defaultEntry);
    }
    return lastHeartbeat_;
  }
  public int getLastHeartbeatCount() {
    return internalGetLastHeartbeat().getMap().size();
  }
  /**
   * <pre>
   * node_id -&gt; timestamp
   * </pre>
   *
   * <code>map&lt;string, int64&gt; last_heartbeat = 1;</code>
   */
  @java.lang.Override
  public boolean containsLastHeartbeat(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetLastHeartbeat().getMap().containsKey(key);
  }
  /**
   * Use {@link #getLastHeartbeatMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Long> getLastHeartbeat() {
    return getLastHeartbeatMap();
  }
  /**
   * <pre>
   * node_id -&gt; timestamp
   * </pre>
   *
   * <code>map&lt;string, int64&gt; last_heartbeat = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.Long> getLastHeartbeatMap() {
    return internalGetLastHeartbeat().getMap();
  }
  /**
   * <pre>
   * node_id -&gt; timestamp
   * </pre>
   *
   * <code>map&lt;string, int64&gt; last_heartbeat = 1;</code>
   */
  @java.lang.Override
  public long getLastHeartbeatOrDefault(
      java.lang.String key,
      long defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetLastHeartbeat().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * node_id -&gt; timestamp
   * </pre>
   *
   * <code>map&lt;string, int64&gt; last_heartbeat = 1;</code>
   */
  @java.lang.Override
  public long getLastHeartbeatOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetLastHeartbeat().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetLastHeartbeat(),
        LastHeartbeatDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.Long> entry
         : internalGetLastHeartbeat().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
      lastHeartbeat__ = LastHeartbeatDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, lastHeartbeat__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.yrrhelp.proto.HeartbeatInfoResponse)) {
      return super.equals(obj);
    }
    com.yrrhelp.proto.HeartbeatInfoResponse other = (com.yrrhelp.proto.HeartbeatInfoResponse) obj;

    if (!internalGetLastHeartbeat().equals(
        other.internalGetLastHeartbeat())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetLastHeartbeat().getMap().isEmpty()) {
      hash = (37 * hash) + LAST_HEARTBEAT_FIELD_NUMBER;
      hash = (53 * hash) + internalGetLastHeartbeat().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.yrrhelp.proto.HeartbeatInfoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yrrhelp.proto.HeartbeatInfoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yrrhelp.proto.HeartbeatInfoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yrrhelp.proto.HeartbeatInfoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yrrhelp.proto.HeartbeatInfoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.yrrhelp.proto.HeartbeatInfoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.yrrhelp.proto.HeartbeatInfoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.yrrhelp.proto.HeartbeatInfoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.yrrhelp.proto.HeartbeatInfoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.yrrhelp.proto.HeartbeatInfoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.yrrhelp.proto.HeartbeatInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.yrrhelp.proto.HeartbeatInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.yrrhelp.proto.HeartbeatInfoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code HeartbeatInfoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:HeartbeatInfoResponse)
      com.yrrhelp.proto.HeartbeatInfoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yrrhelp.proto.Keyvalue.internal_static_HeartbeatInfoResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetLastHeartbeat();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableLastHeartbeat();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yrrhelp.proto.Keyvalue.internal_static_HeartbeatInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yrrhelp.proto.HeartbeatInfoResponse.class, com.yrrhelp.proto.HeartbeatInfoResponse.Builder.class);
    }

    // Construct using com.yrrhelp.proto.HeartbeatInfoResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableLastHeartbeat().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.yrrhelp.proto.Keyvalue.internal_static_HeartbeatInfoResponse_descriptor;
    }

    @java.lang.Override
    public com.yrrhelp.proto.HeartbeatInfoResponse getDefaultInstanceForType() {
      return com.yrrhelp.proto.HeartbeatInfoResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.yrrhelp.proto.HeartbeatInfoResponse build() {
      com.yrrhelp.proto.HeartbeatInfoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.yrrhelp.proto.HeartbeatInfoResponse buildPartial() {
      com.yrrhelp.proto.HeartbeatInfoResponse result = new com.yrrhelp.proto.HeartbeatInfoResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.yrrhelp.proto.HeartbeatInfoResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.lastHeartbeat_ = internalGetLastHeartbeat();
        result.lastHeartbeat_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.yrrhelp.proto.HeartbeatInfoResponse) {
        return mergeFrom((com.yrrhelp.proto.HeartbeatInfoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.yrrhelp.proto.HeartbeatInfoResponse other) {
      if (other == com.yrrhelp.proto.HeartbeatInfoResponse.getDefaultInstance()) return this;
      internalGetMutableLastHeartbeat().mergeFrom(
          other.internalGetLastHeartbeat());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
              lastHeartbeat__ = input.readMessage(
                  LastHeartbeatDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableLastHeartbeat().getMutableMap().put(
                  lastHeartbeat__.getKey(), lastHeartbeat__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Long> lastHeartbeat_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
        internalGetLastHeartbeat() {
      if (lastHeartbeat_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            LastHeartbeatDefaultEntryHolder.defaultEntry);
      }
      return lastHeartbeat_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
        internalGetMutableLastHeartbeat() {
      if (lastHeartbeat_ == null) {
        lastHeartbeat_ = com.google.protobuf.MapField.newMapField(
            LastHeartbeatDefaultEntryHolder.defaultEntry);
      }
      if (!lastHeartbeat_.isMutable()) {
        lastHeartbeat_ = lastHeartbeat_.copy();
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return lastHeartbeat_;
    }
    public int getLastHeartbeatCount() {
      return internalGetLastHeartbeat().getMap().size();
    }
    /**
     * <pre>
     * node_id -&gt; timestamp
     * </pre>
     *
     * <code>map&lt;string, int64&gt; last_heartbeat = 1;</code>
     */
    @java.lang.Override
    public boolean containsLastHeartbeat(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetLastHeartbeat().getMap().containsKey(key);
    }
    /**
     * Use {@link #getLastHeartbeatMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long> getLastHeartbeat() {
      return getLastHeartbeatMap();
    }
    /**
     * <pre>
     * node_id -&gt; timestamp
     * </pre>
     *
     * <code>map&lt;string, int64&gt; last_heartbeat = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Long> getLastHeartbeatMap() {
      return internalGetLastHeartbeat().getMap();
    }
    /**
     * <pre>
     * node_id -&gt; timestamp
     * </pre>
     *
     * <code>map&lt;string, int64&gt; last_heartbeat = 1;</code>
     */
    @java.lang.Override
    public long getLastHeartbeatOrDefault(
        java.lang.String key,
        long defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetLastHeartbeat().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * node_id -&gt; timestamp
     * </pre>
     *
     * <code>map&lt;string, int64&gt; last_heartbeat = 1;</code>
     */
    @java.lang.Override
    public long getLastHeartbeatOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetLastHeartbeat().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearLastHeartbeat() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableLastHeartbeat().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * node_id -&gt; timestamp
     * </pre>
     *
     * <code>map&lt;string, int64&gt; last_heartbeat = 1;</code>
     */
    public Builder removeLastHeartbeat(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableLastHeartbeat().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long>
        getMutableLastHeartbeat() {
      bitField0_ |= 0x00000001;
      return internalGetMutableLastHeartbeat().getMutableMap();
    }
    /**
     * <pre>
     * node_id -&gt; timestamp
     * </pre>
     *
     * <code>map&lt;string, int64&gt; last_heartbeat = 1;</code>
     */
    public Builder putLastHeartbeat(
        java.lang.String key,
        long value) {
      if (key == null) { throw new NullPointerException("map key"); }

      internalGetMutableLastHeartbeat().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * node_id -&gt; timestamp
     * </pre>
     *
     * <code>map&lt;string, int64&gt; last_heartbeat = 1;</code>
     */
    public Builder putAllLastHeartbeat(
        java.util.Map<java.lang.String, java.lang.Long> values) {
      internalGetMutableLastHeartbeat().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }

    // @@protoc_insertion_point(builder_scope:HeartbeatInfoResponse)
  }

  // @@protoc_insertion_point(class_scope:HeartbeatInfoResponse)
  private static final com.yrrhelp.proto.HeartbeatInfoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.yrrhelp.proto.HeartbeatInfoResponse();
  }

  public static com.yrrhelp.proto.HeartbeatInfoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HeartbeatInfoResponse>
      PARSER = new com.google.protobuf.AbstractParser<HeartbeatInfoResponse>() {
    @java.lang.Override
    public HeartbeatInfoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HeartbeatInfoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HeartbeatInfoResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.yrrhelp.proto.HeartbeatInfoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

