// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: keyvalue.proto
// Protobuf Java Version: 4.31.0

package com.yrrhelp.proto;

@com.google.protobuf.Generated
public final class Keyvalue {
  private Keyvalue() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      Keyvalue.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SyncRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SyncRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016keyvalue.proto\"(\n\nPutRequest\022\013\n\003key\030\001 " +
      "\001(\t\022\r\n\005value\030\002 \001(\t\"\031\n\nGetRequest\022\013\n\003key\030" +
      "\001 \001(\t\"\034\n\rDeleteRequest\022\013\n\003key\030\001 \001(\t\"#\n\020H" +
      "eartbeatRequest\022\017\n\007node_id\030\001 \001(\t\"<\n\013Sync" +
      "Request\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\022\021\n\ti" +
      "s_delete\030\003 \001(\010\")\n\010Response\022\016\n\006status\030\001 \001" +
      "(\t\022\r\n\005value\030\002 \001(\t2\270\001\n\007KvStore\022\035\n\003Put\022\013.P" +
      "utRequest\032\t.Response\022\035\n\003Get\022\013.GetRequest" +
      "\032\t.Response\022#\n\006Delete\022\016.DeleteRequest\032\t." +
      "Response\022)\n\tHeartbeat\022\021.HeartbeatRequest" +
      "\032\t.Response\022\037\n\004Sync\022\014.SyncRequest\032\t.Resp" +
      "onseB\025\n\021com.yrrhelp.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PutRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PutRequest_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DeleteRequest_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_HeartbeatRequest_descriptor,
        new java.lang.String[] { "NodeId", });
    internal_static_SyncRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SyncRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SyncRequest_descriptor,
        new java.lang.String[] { "Key", "Value", "IsDelete", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Status", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
